# Generated by Django 2.0.1 on 2018-01-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
