# Generated by Django 2.0.1 on 2018-01-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0003_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='question_id',
            new_name='question',
        ),
    ]
